### ISSUE TITLE
TODO: Add streaming actions

### ISSUE THREAD

**Issue by anzev** [xflows/clowdflows-backend#1]
Related to [frontend issue 1](https://github.com/xflows/clowdflows-webapp/issues/1).

Add support for working with streaming widgets:
- [ ] add stop/start actions for workflows with streaming widgets
- [ ] streaming workflow API view
- [ ] streaming widget results API view
