### ISSUE TITLE
TODO: Modify category hierarchy

### ISSUE THREAD

**Issue by janezkranjc** [xflows/clowdflows-backend#5]
- [x] Implement a setting that defines a category hierachy - an ordered dictionary of category names as keys and lists of packages as values.

- [x] Implement a method that executes in the settings that takes the new setting and extracts the packages from it and appends it to django apps.

- [x] Implement a new view that provides a JSON with top level hierarchies defined in the setting which includes categories and widgets for that setting. Only include widgets (and categories) that belong in the packages that are list members of the value of the corresponding key (top level node).

**Comment by mperice** [comment]
This is addressed in commit 6cda59e8a2dff73d59ca80ce90a5d4edb49df448
